### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 2332370844** [sha3sha3/UE-EasyKafka#3]
Hello, may I ask if I can write this part of C++

**Comment by 2332370844** [comment]
Are the two blueprint files of Producer and Consumer logically written in two empty actor blueprints? How to use these two blueprint files? Can you make a project about this plugin, looking forward to your news,

**Comment by sha3sha3** [comment]
hey @2332370844 
Thanks for your interest in this project
They are two singleton classes!
Just follow the documentation, should be enough.
I will create a demo project when i can spare some time.
