### ISSUE TITLE
Why cannot receive message?

### ISSUE THREAD

**Issue by 2332370844** [sha3sha3/UE-EasyKafka#4]
hi, 
    I use your UE plugin in my UE5.0.3 project by blueprint, but cannot get message after I registered the consumer .
    And I found in blueprint node: CreateConsumer, the username and password are both null, is it right? 
![微信截图_20230906165546](https://github.com/sha3sha3/UE-EasyKafka/assets/57941370/8c9294a9-cb3a-46aa-a555-35de16f88d3d)

**Comment by sha3sha3** [comment]
Hey @2332370844 

Please use the highest verbose logging and attach logs so that I can assist.

**Comment by sha3sha3** [comment]
Issue closed, no response!
