### ISSUE TITLE
How can I include Easykafka in my own plugin?

### ISSUE THREAD

**Issue by vincenthng** [sha3sha3/UE-EasyKafka#5]
I am developing a plugin which needs to send message to Kafka(as a producer), so I tried to include EasyKafka to complete the message sending part. However, I got some trouble when using `#include "EasyKafka/Public/EasyKafkaSubsystem.h"`.

The editor consistantly report fatal error C1083 “EasyKafka/Public/EasyKafkaSubsystem.h”: No such file or directory.

According to the documentation,  I have already add the modules in PrivateDependencyModuleNames
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/16207759/034b78e0-a066-419a-b580-458a39dff527)
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/16207759/cc213531-c977-4f06-b50a-bc7113f504e9)

and also I tried to modify the .uplugin file and add the EasyKafka into plugin and addtional dependencies
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/16207759/7e8d2118-f696-4afe-b95e-ddb0d294b660)

If I made some basic mistake, please don't hesitate to tell me, since I am still a beginner in UE.

**Comment by sha3sha3** [comment]
Hey!

Quite easy, you have to add the modules to your plugin <YourModule>.build.cs
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/40597819/839bb201-8674-40d7-b952-3c46b293630c)
Then this is how .uplugin should look like
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/40597819/4ef313f6-d51b-42a2-a477-652e4b426c45)
Lastly you can include the sub-system like this:
![image](https://github.com/sha3sha3/UE-EasyKafka/assets/40597819/7fc9fc5f-f7fc-4874-afc3-5946e0e64c26)
Attached a reference plugin
[KafkaMod.zip](https://github.com/sha3sha3/UE-EasyKafka/files/12790165/KafkaMod.zip)

**Comment by vincenthng** [comment]
> Hey!
> 
> Quite easy, you have to add the modules to your plugin .build.cs ![image](https://user-images.githubusercontent.com/40597819/272193443-839bb201-8674-40d7-b952-3c46b293630c.png) Then this is how .uplugin should look like ![image](https://user-images.githubusercontent.com/40597819/272193898-4ef313f6-d51b-42a2-a477-652e4b426c45.png) Lastly you can include the sub-system like this: ![image](https://user-images.githubusercontent.com/40597819/272194269-7fc9fc5f-f7fc-4874-afc3-5946e0e64c26.png) Attached a reference plugin [KafkaMod.zip](https://github.com/sha3sha3/UE-EasyKafka/files/12790165/KafkaMod.zip)

Thanks a lot for the reply and the attachment! I'll try it out~

Furthermore, I do have 2 more questions
1. Does EasyKafka support the platforms like Xbox/PS5?
2. Does EasyKafka build up a keep-alive connection while communicate with Kafka queue or just use a polling strategy?

**Comment by sha3sha3** [comment]
Hey @vincenthng 
By default **socket.keepalive.enable**  is disabled.
You can enable it by setting it to true.
Regarding **Xbox/PS5** i don't have development kits, thus they are not supported.
I might try to add support but without testing.

**Comment by sha3sha3** [comment]
Hey @vincenthng 
I will consider this issue solved.

**Comment by sha3sha3** [comment]
Hey @vincenthng 
 will consider this issue solved.

**Comment by AdrienHoule** [comment]
Hi so I tried to use your example plugins but ends up with weird unrelated issues when buillding your simple example. 
But everything works fine in blueprint.  Also my build.cs and .uplugin are exactly the same  as your example. 

Here are the issues wich are I think totally unrelated

1>C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\AudioMixer\Public\Quartz\AudioMixerQuantizedCommands.h(31): error C2838: 'PlaySoundW' : nom qualifié non conforme dans une déclaration de membre
1>C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\AudioMixer\Public\Quartz\AudioMixerQuantizedCommands.h(31): error C2440: 'return' : impossible de convertir de 'BOOL (__cdecl *)(LPCWSTR,HMODULE,DWORD)' en 'EQuartzCommandType'
1>C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\AudioMixer\Public\Quartz\AudioMixerQuantizedCommands.h(31): note: Aucun contexte dans lequel cette conversion est possible
1>C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\TextureCube.h(74): error C3668: 'UTextureCube::UpdateResourceW' : la méthode comprenant le spécificateur de substitution 'override' n'a substitué aucune méthode de la classe de base
1>C:\Program Files\Epic Games\UE_5.3\Engine\Source\Runtime\Engine\Classes\Engine\CanvasRenderTarget2D.h(43): error C3668: 'UCanvasRenderTarget2D::UpdateResourceW' : la méthode comprenant le spécificateur de substitution 'override' n'a substitué aucune méthode de la classe de base
